# Generated by Django 5.1.5 on 2025-04-15 12:50

import django.db.models.deletion
import risktrades.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=50)),
                ('risk_pips', models.IntegerField()),
                ('risk_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_tsh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gain_pips', models.IntegerField()),
                ('gain_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gain_tsh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mt5_chart', models.ImageField(blank=True, null=True, upload_to=risktrades.models.risktrade_image_path)),
                ('tradeview_chart', models.ImageField(blank=True, null=True, upload_to=risktrades.models.risktrade_image_path)),
                ('mt5_positions', models.ImageField(blank=True, null=True, upload_to=risktrades.models.risktrade_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('day_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risktrades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
