# Generated by Django 5.1.5 on 2025-04-15 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(blank=True, max_length=6, null=True)),
                ('traders_idea_name', models.CharField(blank=True, max_length=15, null=True)),
                ('trade_signal', models.CharField(blank=True, choices=[('BUYS', 'BUYS'), ('SELLS', 'SELLS')], max_length=5, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea_candle', models.ImageField(blank=True, null=True, upload_to='idea_candles/')),
                ('idea_candle_two', models.ImageField(blank=True, null=True, upload_to='idea_candle_two/')),
                ('youtube_candle', models.ImageField(blank=True, null=True, upload_to='youtube/')),
                ('volumetic_rejection_candle', models.ImageField(blank=True, null=True, upload_to='volumetic_rejection_candles/')),
                ('fibonnaci_candle', models.ImageField(blank=True, null=True, upload_to='fibonnaci_candles/')),
                ('ICT_killzone_candle', models.ImageField(blank=True, null=True, upload_to='ICT_killzone_candles/')),
                ('ichimoku_candle', models.ImageField(blank=True, null=True, upload_to='ichimoku_candles/')),
                ('ema_cross_alert_candle', models.ImageField(blank=True, null=True, upload_to='ema_cross_alert_candles/')),
                ('ICT_institutional_order_candle', models.ImageField(blank=True, null=True, upload_to='ICT_institutional_order_candles/')),
                ('daily_high_low_candle', models.ImageField(blank=True, null=True, upload_to='daily_high_low_candle/')),
                ('all_indicators_candle', models.ImageField(blank=True, null=True, upload_to='all_indicators_candle/')),
                ('blog_trade_post_candle', models.ImageField(blank=True, null=True, upload_to='blog_trade_post_candle/')),
                ('blog_mt5_post_candle', models.ImageField(blank=True, null=True, upload_to='blog_mt5_post_candle/')),
                ('stoploss_candle', models.ImageField(blank=True, null=True, upload_to='stoploss_candle/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade reason',
                'verbose_name_plural': 'Trade reasons',
            },
        ),
    ]
