# Generated by Django 5.1.5 on 2025-04-15 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(blank=True, max_length=6, null=True)),
                ('traders_idea_name', models.CharField(blank=True, max_length=15, null=True)),
                ('trade_signal', models.CharField(blank=True, choices=[('BUYS', 'BUYS'), ('SELLS', 'SELLS')], max_length=5, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea_candle', models.ImageField(blank=True, null=True, upload_to='idea_candles/')),
                ('idea_candle_two', models.ImageField(blank=True, null=True, upload_to='idea_candle_two/')),
                ('youtube_candle', models.ImageField(blank=True, null=True, upload_to='youtube/')),
                ('daily_candle', models.ImageField(blank=True, null=True, upload_to='daily_candles/')),
                ('four_hour_candle', models.ImageField(blank=True, null=True, upload_to='four_hour_candles/')),
                ('line_graph_candle', models.ImageField(blank=True, null=True, upload_to='line_graph_candles/')),
                ('signal_candle', models.ImageField(blank=True, null=True, upload_to='signal_candles/')),
                ('hour_candle', models.ImageField(blank=True, null=True, upload_to='hour_candles/')),
                ('two_hour_candle', models.ImageField(blank=True, null=True, upload_to='two_hour_candles/')),
                ('entry_candle', models.ImageField(blank=True, null=True, upload_to='entry_candle/')),
                ('breakeven_candle', models.ImageField(blank=True, null=True, upload_to='breakeven_candle/')),
                ('take_profit_one_candle', models.ImageField(blank=True, null=True, upload_to='take_profit_one_candle/')),
                ('take_profit_two_candle', models.ImageField(blank=True, null=True, upload_to='take_profit_two_candle/')),
                ('stoploss_candle', models.ImageField(blank=True, null=True, upload_to='stoploss_candle/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade detail',
                'verbose_name_plural': 'Trade details',
            },
        ),
    ]
