# Generated by Django 5.1.5 on 2025-04-15 12:50

import django.db.models.deletion
import games.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(choices=[('Educational', 'Educational'), ('Action', 'Action'), ('Puzzle', 'Puzzle'), ('Adventure', 'Adventure'), ('For Fun', 'For Fun'), ('Creative', 'Creative'), ('Other', 'Other')], default='Other', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=games.models.game_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
