# Generated by Django 5.1.5 on 2025-04-15 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0)),
                ('pieces', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Educational', 'Educational'), ('Action', 'Action'), ('Puzzle', 'Puzzle'), ('Plush', 'Plush'), ('For Fun', 'For Fun'), ('Creative', 'Creative'), ('Other', 'Other')], default='Other', max_length=50)),
                ('age_group', models.CharField(choices=[('0-2 years', '0-2 years'), ('3-5 years', '3-5 years'), ('6-8 years', '6-8 years'), ('9+ years', '9+ years')], default='3-5 years', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='toy_images/')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
