# Generated by Django 5.1.5 on 2025-04-15 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pieces', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='puzzle_images/')),
                ('age_group', models.CharField(choices=[('under_5', 'Under 5 years'), ('under_10', 'Under 10 years'), ('under_18', 'Under 18 years'), ('above_18', '18 years and above')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
